# Generated by Django 5.2.8 on 2025-11-29 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='RSS kaynağının adı (örn: BBC News)', max_length=255)),
                ('url', models.URLField(help_text="RSS feed URL'si", unique=True)),
                ('category', models.CharField(help_text='Kategori (örn: Teknoloji, Spor, Siyaset)', max_length=100)),
                ('frequency_minutes', models.IntegerField(choices=[(15, '15 dakika'), (30, '30 dakika'), (60, '1 saat'), (240, '4 saat'), (480, '8 saat'), (1440, '1 gün')], default=60, help_text='Tarama sıklığı (dakika cinsinden)')),
                ('is_active', models.BooleanField(default=True, help_text='Kaynak aktif mi?')),
                ('last_checked', models.DateTimeField(blank=True, help_text='Son tarama zamanı', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSS Kaynağı',
                'verbose_name_plural': 'RSS Kaynakları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Haber başlığı', max_length=500)),
                ('slug', models.SlugField(help_text="URL'de kullanılacak slug", unique=True)),
                ('content', models.TextField(help_text='Haber içeriği (HTML destekler)')),
                ('excerpt', models.TextField(blank=True, help_text='Haber özeti (SEO için)', max_length=500)),
                ('featured_image', models.ImageField(blank=True, help_text='Haber başlık görseli', null=True, upload_to='articles/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Görselin alt metni (SEO için)', max_length=255)),
                ('category', models.CharField(help_text='Kategori', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Etiketler (virgülle ayrılmış)', max_length=500)),
                ('original_url', models.URLField(blank=True, help_text="Orijinal haber URL'si (RSS'den gelmişse)")),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayınlandı'), ('archived', 'Arşivlendi')], default='draft', help_text='Yayın durumu', max_length=20)),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Yapay zeka tarafından mı üretildi?')),
                ('is_ai_image', models.BooleanField(default=False, help_text='Görsel yapay zeka tarafından mı üretildi?')),
                ('views_count', models.IntegerField(default=0, help_text='Görüntülenme sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Yayınlanma tarihi', null=True)),
                ('author', models.ForeignKey(help_text='Yazarı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='authors.author')),
                ('rss_source', models.ForeignKey(blank=True, help_text='Kaynaklandığı RSS kaynağı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.rsssource')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_articl_publish_62720b_idx'), models.Index(fields=['category'], name='news_articl_categor_5c78fc_idx'), models.Index(fields=['status'], name='news_articl_status_a95c4c_idx'), models.Index(fields=['author'], name='news_articl_author__94d1eb_idx')],
            },
        ),
    ]
